# declare Traefik deployment
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: foodlist-app
  labels:
    app: foodlist-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodlist-app
  template:
    metadata:
      labels:
        app: foodlist-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                    - preemptible-workers
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - foodlist-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: foodlist-app
        image: "gcr.io/mattburman/0b5e97cdaf6f@sha256:97af9734d6df7fdc77b95006f39de5b3759acc2b6cf0650c806d4b5e0b77d401"