apiVersion: v1
kind: Service
metadata:
  name: foodlist-list
spec:
  selector:
    app: foodlist-list
  ports:
  - name: http
    targetPort: 4000
    port: 80
  - name: https
    targetPort: 4000
    port: 443
